# Generated by Django 4.2.1 on 2023-06-04 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mangas',
            fields=[
                ('id_anime', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('capitulos', models.IntegerField()),
                ('autor', models.CharField(max_length=100)),
                ('Ano_de_lancamento', models.IntegerField()),
            ],
        ),
    ]
