# Generated by Django 4.2.1 on 2023-06-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animes',
            old_name='ano',
            new_name='data_de_lancamento',
        ),
        migrations.RenameField(
            model_name='animes',
            old_name='eps',
            new_name='episodios',
        ),
        migrations.RenameField(
            model_name='animes',
            old_name='title',
            new_name='titulo',
        ),
    ]
