# Generated by Django 4.2.1 on 2023-06-04 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_rename_ano_animes_data_de_lancamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animes',
            old_name='data_de_lancamento',
            new_name='Ano_de_lancamento',
        ),
    ]
